services:
  demo-app-zone-a:
    environment:
      DEMO_LOGSTASH_URL: ""
      OTEL_EXPORTER_OTLP_ENDPOINT: http://datadog-agent-zone-a:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
    labels:
      com.datadoghq.ad.logs: '[{"source":"go","service":"payments-api"}]'

  demo-app-zone-b:
    environment:
      DEMO_LOGSTASH_URL: ""
      OTEL_EXPORTER_OTLP_ENDPOINT: http://datadog-agent-zone-b:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
    labels:
      com.datadoghq.ad.logs: '[{"source":"go","service":"lending-api"}]'

  datadog-agent-zone-a:
    image: gcr.io/datadoghq/agent:7
    hostname: node-zone-a
    environment:
      DD_API_KEY: ${DD_API_KEY:?DD_API_KEY belum di-set. Isi di .env (Datadog > Organization Settings > API Keys)}
      DD_SITE: ${DD_SITE:-datadoghq.com}
      DD_HOSTNAME: node-zone-a
      DD_TAGS: "zone:zone-a env:poc"
      DD_APM_ENABLED: "true"
      DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT: "0.0.0.0:4317"
      DD_PROCESS_AGENT_ENABLED: "false"
      DD_LOGS_ENABLED: "true"
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: "true"
      DD_CONTAINER_EXCLUDE_LOGS: "name:.*"
      DD_CONTAINER_INCLUDE_LOGS: "name:demo-app-zone-a"
    volumes:
      - ./datadog/openmetrics-zone-a.yaml:/etc/datadog-agent/conf.d/openmetrics.d/conf.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - zone_a_net

  datadog-agent-zone-b:
    image: gcr.io/datadoghq/agent:7
    hostname: node-zone-b
    environment:
      DD_API_KEY: ${DD_API_KEY:?DD_API_KEY belum di-set. Isi di .env (Datadog > Organization Settings > API Keys)}
      DD_SITE: ${DD_SITE:-datadoghq.com}
      DD_HOSTNAME: node-zone-b
      DD_TAGS: "zone:zone-b env:poc"
      DD_APM_ENABLED: "true"
      DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT: "0.0.0.0:4317"
      DD_PROCESS_AGENT_ENABLED: "false"
      DD_LOGS_ENABLED: "true"
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: "true"
      DD_CONTAINER_EXCLUDE_LOGS: "name:.*"
      DD_CONTAINER_INCLUDE_LOGS: "name:demo-app-zone-b"
    volumes:
      - ./datadog/openmetrics-zone-b.yaml:/etc/datadog-agent/conf.d/openmetrics.d/conf.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - zone_b_net
