input {
  http {
    port => 8080
    codec => json
  }
}

filter {
  mutate {
    add_field => {
      "event_dataset" => "demo_app.access"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "demo-app-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
