input {
  http {
    port => 8080
    codec => json
  }
  beats {
    port => 5044
  }
}

filter {
  if [winlog] {
    mutate {
      add_field => {
        "event_dataset" => "windows.eventlog"
        "[@metadata][index]" => "windows-eventlog"
      }
    }
  } else {
    mutate {
      add_field => {
        "event_dataset" => "demo_app.access"
        "[@metadata][index]" => "demo-app-logs"
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][index]}-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
